### ISSUE TITLE
不是很理解ALPF和AHPF如何做到低通和高通的？

### ISSUE THREAD

**Issue by lmomoy** [Linwei-Chen/FreqFusion#11]
特征图似乎并没有在频域上操作，希望请教一下title的问题

**Comment by Linwei-Chen** [comment]
感谢关注，论文主要是使用不同特性的高低通滤波对特征进行优化，优化的思路是物体整体特征应当更稳定一致，体现在频域上是高频信号少，对于边缘部分应该边缘清晰，体现在频域上是高频信号多。对此可以学习使用不同高低通的自适应滤波相应处理。
