### ISSUE TITLE
关于ALPF generator，AHPF generator以及Offset generator的理解

### ISSUE THREAD

**Issue by windyjunfeng** [Linwei-Chen/FreqFusion#12]
您好，想请教一下如何确保ALPF generator得到的一定是K\*K的低通滤波器呢？因为看论文中图5(b)的频域可视化，有些学习到的参数明显是高通滤波器。同样，如何确保AHPF generator得到的一定是K\*K的高通滤波器呢？
另外，Offset generator是不是借鉴了可变形卷积的思路呢？我个人理解是将可变形卷积预测卷积核的偏移量变成划分的G组的偏移量，然后将原本的偏移量表示进一步拆解成幅度和方向。
期待您的回复，感谢！

**Comment by Linwei-Chen** [comment]
感谢关注，这个图是说明为何需要在initial fusion里引入AHPF来增强高频。
如何生成高频和低频可参考：
Instance Segmentation in the Dark
Dynamic High-Pass Filtering and Multi-Spectral Attention for Image Super-Resolution

**Comment by windyjunfeng** [comment]
感谢您的回复，看了这两篇文章后明白了。
