### ISSUE TITLE
您好。想请问以下使用FreqFusion的位置和方式有什么注意的吗？我使用了之后效果是变差的。

### ISSUE THREAD

**Issue by lcl-git-3d** [Linwei-Chen/FreqFusion#32]
我有x12,xm,xl均为[B,C,H,W]的特征图
我先利用[nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2)这种方式，将xm,xl分别上采样为[B,C,2*H,2*W]以及[B,C,4*H,4*W].
然后使用参照了FPN的方式使用了FreqFusion:
 _,xm,x12_up=self.ff1(hr_feat=xm, lr_feat=x12)
 ym=xm+x12_up
 _,xl,ym_up=self.ff2(hr_feat=xl,lr_feat=ym)
yl=xl+ym_up
然后最终通过下采样将融合后的特征恢复为原本的[B,C,H,W]
Fusion_f=self.downsample(yl)
不知道什么原因，精度随着训练的epoch的增加而降低，也就是说第一轮的epoch的训练效果是最好的。
我改动的地方有：
因为使用的过程中，遇到了这个错误;RuntimeError: expected scalar type Half but found Float
所以我便把输入到cafer的参数添加了.to(torch.float16)的格式转换解决了报错。
期待您的回复！

**Comment by Linwei-Chen** [comment]
感谢关注！注意将FreqFusion从深到浅地替换模型中上采样以及特征融合的部位

**Comment by lcl-git-3d** [comment]
谢谢您的回复。理解上我还是有一点疑问：
1.我提取的特征xd,xm,xl是由深至浅的[B,C,H,W]的特征图，它们维度一样。我为了构造多尺度，所以通过普通上采样的方式，将xm,xl分别上采样为[B,C,2H,2W]以及[B,C,4H,4W]。然后按照您说的方式，
从深到浅地替换模型中上采样以及特征融合的部位：
_,xm,xd_up=self.ff1(hr_feat=xm, lr_feat=xd)
ym=xm+xd_up
_,xl,ym_up=self.ff2(hr_feat=xl,lr_feat=ym)
yl=xl+ym_up
但是效果会变差，请问对于像xd,xm,xl这种由深至浅且相同维度[B,C,H,W]的特征图，应该如何去使用您的方便比较好呢？或者说如何去构建多尺度再使用您的方法进行融合比较好呢？
期待您的详细解答，非常感谢！！

**Comment by lcl-git-3d** [comment]
请问方便告诉我您的邮件或者微信吗，方便通过邮箱或者微信向您请教吗？

**Comment by Linwei-Chen** [comment]
Charleschen2013@163.com
