### ISSUE TITLE
请问有不依赖mmcv的FreqFusion的实现方式吗？mmcv装起来太费劲了

### ISSUE THREAD

**Issue by ZXMMD** [Linwei-Chen/FreqFusion#39]

**Comment by Linwei-Chen** [comment]
感谢关注！已经更新过不需要mmcv的版本：
https://github.com/Linwei-Chen/FreqFusion/blob/main/FreqFusion.py

**Comment by ZXMMD** [comment]
非常感谢！这个可以正常使用，但是会占用很大的显存，请问有什么比较好的解决方法吗？

**Comment by Linwei-Chen** [comment]
1. 可以使用import torch.utils.checkpoint as checkpoint，即torch里的checkpoint机制来减少显存
2. 最佳方案是使用mmcv调用其cuda算子
可参考：
https://github.com/Linwei-Chen/FreqFusion/issues/3#issuecomment-2434644964

**Comment by Linwei-Chen** [comment]
mmcv installation：
mmcv 1.x 
pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html
Ref: https://mmcv.readthedocs.io/en/master/get_started/installation.html

mmcv 2.x
pip install mmcv==2.2.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.4/index.html
Ref: https://mmcv.readthedocs.io/en/latest/get_started/installation.html
